import pandas as pd
projets = pd.read_json(path_or_buf="Data/concours_projet_realisation.jsonl", lines=True,encoding="utf-8",orient="records")

# Créer une colonne thématique général (santé, numérique, environnement, énergie, agriculture)
print(projets["THEMATIQUE"].unique())

liste = ['numérique' 'agriculture innovante'
 'énergies renouvelables, stockage et systèmes énergétiques' 'santé'
 'transport et mobilité durable' 'sécurité et cybersécurité' 'french fab'
 'alimentation intelligente'
 'écosystèmes terrestres, aquatiques et marins'
 'agriculture, industrie et sylviculture éco-efficientes'
 'expositions chroniques et risques sanitaires'
 'performance environnementale des bâtiments' 'economie circulaire'
 'espace' 'société inclusive et solidaire' 'numérique deeptech'
 'efficacité en énergie et en ressources' 'numérique deep tech'
 'eau et biodiversité' 'santé - bioproduction' 'santé bioproduction'
 'sécurité cybersécurité'
 'transition écologique applications jop paris 2024' 'économie circulaire'
 'adaptation au changement climatique' 'santé – chirurgie du futur'
 'numérique deep tech – applications jop paris 2024' 'ville en transition'
 'french fab – matériaux innovants' 'french fab - matériaux innovants'
 'santé - chirurgie du futur' 'alimentation durable pour la santé'
 'santé situations d’urgences' 'french fab industrie du futur'
 'industrie et agriculture éco-efficientes'
 'energies renouvelables, stockage et systèmes énergétiques'
 'cybersécurité' 'hydrogène'
 'adaptation des territoires au changement climatique et  métrologie des expositions environnementales'
 'réduction de l’empreinte écologique du numérique'
 'santé - santé mentale et diagnostics rapides et nomades'
 'energies renouvelables, stockage et systèmes énergétiques dont hydrogène'
 'enjeux de la transition écologique dans l’industrie et l’agriculture'
 'mobilité durable et intelligente' 'protéines et ferments du futur'
 'santé - diagnostic, dépistage et surveillance des pathologies'
 'transformer les industries culturelles et créatives grâce au numérique'
 ': adaptation de l’agriculture au changement climatique et gestion des aléas'
 'adaptation des territoires au changement climatique atténuation de ses effets,prévention des risques et métrologie des expositions environnementales'
 'performance environnementale et énergétique des bâtiments'
 'économie circulaire (y compris recyclage des métaux critiques)'
 'santé - dispositifs médicaux innovants'
 "réduction de l'empreinte environnementale" 'french fab – industrie 4.0'
 'santé - outils de modélisation  simulation numériquepour le développement de biomédicaments'
 'energies, ressources et milieux naturels'
 'transports, mobilités, villes et bâtiments durables'
 'énergies, ressources et milieux naturels']